<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Sakolee.Workers-b9a55ef0-f63d-4039-8b16-3dfe8ea459a0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.NetCore" Version="1.8.14" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sakolee.Shared\Sakolee.Shared.csproj" />
    <ProjectReference Include="..\Sakolee.Infrastructure\Sakolee.Infrastructure.csproj" />
    <ProjectReference Include="..\Sakolee.Application\Sakolee.Application.csproj" />
  </ItemGroup>
</Project>
