<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Persistence\Migrations\20260921092732_AddSessionTable.cs" />
    <Compile Remove="Persistence\Migrations\20260921092732_AddSessionTable.Designer.cs" />
    <Compile Remove="Persistence\Migrations\20260921124053_Location.cs" />
    <Compile Remove="Persistence\Migrations\20260921124053_Location.Designer.cs" />
    <Compile Remove="Persistence\Migrations\20260921141731_UpdateFamilyStatusAuditing.cs" />
    <Compile Remove="Persistence\Migrations\20260921141731_UpdateFamilyStatusAuditing.Designer.cs" />
    <Compile Remove="Persistence\Migrations\20260922070930_AddClassSessions.cs" />
    <Compile Remove="Persistence\Migrations\20260922070930_AddClassSessions.Designer.cs" />
    <Compile Remove="Persistence\Migrations\20260922072844_AddClassSessionsTable.cs" />
    <Compile Remove="Persistence\Migrations\20260922072844_AddClassSessionsTable.Designer.cs" />
    <Compile Remove="Persistence\Migrations\20260922073617_AddClassSessionsTable.cs" />
    <Compile Remove="Persistence\Migrations\20260922073617_AddClassSessionsTable.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sakolee.Shared\Sakolee.Shared.csproj" />
    <ProjectReference Include="..\Sakolee.Application\Sakolee.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.14" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.14" />
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
